networks:
  backend:
    driver: bridge

services:
  backend-db:
    image: postgres:latest
    container_name: demolish-db
    environment:
      PGDATA: /tmp
      POSTGRES_DB: demolish
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_DEFAULT_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./docker/data/db-backend:/var/lib/postgresql/data"
    networks:
      - backend

  backend:
    build: .
    container_name: demolish-backend
    ports:
      - "3000:3000"
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - backend-db
    networks:
      - backend

  # net:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloud
  #   networks: 
  #     - backend
  #   env_file: .env
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=$TUNNEL_TOKEN
